apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: gp3